/**
 * Test category for AI-generated test assertions.
 */
export type TestCategory =
  | 'status'
  | 'body_structure'
  | 'data_validation'
  | 'performance'
  | 'edge_case';

/**
 * A single AI-generated test assertion.
 */
export interface GeneratedTest {
  name: string;
  category: TestCategory;
  assertion: string;
  script: string;
}

/**
 * Complete test suite generated by AI from a response.
 */
export interface TestSuite {
  tests: GeneratedTest[];
  summary: string;
}

/**
 * Confidence level for AI debug analysis.
 */
export type ConfidenceLevel = 'high' | 'medium' | 'low';

/**
 * Priority level for suggested fixes.
 */
export type FixPriority = 'critical' | 'recommended' | 'optional';

/**
 * A single fix suggestion from the debug assistant.
 */
export interface DebugSuggestion {
  title: string;
  description: string;
  code?: string;
  priority: FixPriority;
}

/**
 * Complete debug analysis from AI.
 */
export interface DebugAnalysis {
  diagnosis: {
    cause: string;
    confidence: ConfidenceLevel;
    explanation: string;
  };
  suggestions: DebugSuggestion[];
  relatedDocs?: string[];
}

/**
 * AI chat message.
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

/**
 * AI usage tracking for the current billing period.
 */
export interface AIUsage {
  used: number;
  limit: number;
  remaining: number;
  resetDate: string;
}
