/**
 * Standard error codes used across the API.
 */
export const API_ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_ERROR: 'AUTH_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    NOT_FOUND: 'NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    RATE_LIMITED: 'RATE_LIMITED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    SSRF_BLOCKED: 'SSRF_BLOCKED',
    EXECUTION_ERROR: 'EXECUTION_ERROR',
    AI_ERROR: 'AI_ERROR',
    AI_LIMIT_EXCEEDED: 'AI_LIMIT_EXCEEDED',
};
//# sourceMappingURL=api.types.js.map