import { dbProvider } from '../../data/database-provider';
import crypto from 'crypto';

/**
 * Environment service — CRUD + variable resolution helpers.
 * Business logic only — no req/res access.
 * Uses the AtxDataProvider boundary for persistence.
 */
export class EnvironmentService {
  /**
   * Create a new environment for a user.
   */
  async create(
    userId: string,
    name: string,
    variables: Array<{ key: string; value: string; type?: string; description?: string }> = [],
  ) {
    const env = await dbProvider.environments.create({
      id: crypto.randomUUID(),
      userId,
      name,
      variables: variables.map(v => ({
        key: v.key,
        value: v.value,
        type: (v.type === 'secret' ? 'secret' : 'text') as 'text' | 'secret',
        description: v.description || '',
      })),
      isDefault: false,
    });
    return { ...env, _id: env.id };
  }

  /**
   * List all environments for a user.
   * Secret variable values are masked with "••••••".
   */
  async list(userId: string) {
    const envs = await dbProvider.environments.listByUser(userId);
    return envs.map((env) => ({
      ...env,
      _id: env.id,
      variables: env.variables.map((v) => ({
        ...v,
        value: v.type === 'secret' ? '••••••' : v.value,
      })),
    }));
  }

  /**
   * Get a single environment with REAL values (owner-only, for editing).
   */
  async getById(userId: string, envId: string) {
    const env = await dbProvider.environments.getById({ id: envId, userId });
    if (!env) return null;
    return { ...env, _id: env.id };
  }

  /**
   * Get a flat Record<key, value> of resolved variables.
   * Returns real values even for secrets (used by executor).
   */
  async getVariables(userId: string, envId: string): Promise<Record<string, string>> {
    const env = await dbProvider.environments.getById({ id: envId, userId });
    if (!env) return {};

    const vars: Record<string, string> = {};
    env.variables.forEach((v) => {
      vars[v.key] = v.value;
    });
    return vars;
  }

  /**
   * Update or insert multiple variables into an environment
   */
  async updateVariables(userId: string, envId: string, updates: Record<string, string>): Promise<void> {
    const env = await dbProvider.environments.getById({ id: envId, userId });
    if (!env) return;

    for (const [key, value] of Object.entries(updates)) {
      const existing = env.variables.find((v) => v.key === key);
      if (existing) {
        existing.value = value;
      } else {
        env.variables.push({ 
          key, 
          value, 
          type: 'text', 
          description: 'Generated by pre-request script' 
        });
      }
    }

    await dbProvider.environments.update({
      id: envId,
      userId,
      variables: env.variables,
    });
  }

  /**
   * Update an environment (name, variables).
   */
  async update(userId: string, envId: string, updates: Partial<{ name: string; variables: any[] }>) {
    const payload: any = {};
    if (updates.name !== undefined) payload.name = updates.name;
    if (updates.variables !== undefined) {
      payload.variables = updates.variables.map((v: any) => ({
        key: v.key,
        value: v.value,
        type: v.type === 'secret' ? 'secret' : 'text',
        description: v.description || '',
      }));
    }

    const env = await dbProvider.environments.update({
      id: envId,
      userId,
      ...payload,
    });

    return { ...env, _id: env.id };
  }

  /**
   * Delete an environment.
   */
  async delete(userId: string, envId: string): Promise<boolean> {
    const env = await dbProvider.environments.getById({ id: envId, userId });
    if (!env) return false;
    await dbProvider.environments.delete({ id: envId, userId });
    return true;
  }

  /**
   * Set an environment as the default.
   */
  async setDefault(userId: string, envId: string): Promise<void> {
    await dbProvider.environments.setDefault({ id: envId, userId });
  }
}
